services:
  - type: web
    name: voice-enhancer-ai
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python run.py
    plan: starter
    healthCheckPath: /api/health
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: DEBUG
        value: false
      - key: LOG_LEVEL
        value: INFO
    disk:
      name: voice-enhancer-storage
      mountPath: /app/uploads
      sizeGB: 5